### ISSUE TITLE
报了一个错误。麻烦帮忙看一下

### ISSUE THREAD

**Issue by AlphaCatMeow** [lufficc/LightAdapter#1]
java.lang.NullPointerException: you don't register this model
 at com.lufficc.lightadapter.LightAdapter.getItemViewType(LightAdapter.java:99)
 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5014)
 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
 at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2843)
 at android.view.View.measure(View.java:17782)
 at android.widget.RelativeLayout.measureChild(RelativeLayout.java:816)
 at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:561)
 at android.view.View.measure(View.java:17782)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
 at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
 at android.view.View.measure(View.java:17782)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
 at android.view.View.measure(View.java:17782)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
 at android.view.View.measure(View.java:17782)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
 at android.view.View.measure(View.java:17782)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2644)
 at android.view.View.measure(View.java:17782)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2384)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1399)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1623)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1277)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6478)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
 at android.view.Choreographer.doCallbacks(Choreographer.java:603)
 at android.view.Choreographer.doFrame(Choreographer.java:572)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
 at android.os.Handler.handleCallback(Handler.java:815)
 at android.os.Handler.dispatchMessage(Handler.java:104)
 at android.os.Looper.loop(Looper.java:194)
 at android.app.ActivityThread.main(ActivityThread.java:5548)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by lufficc** [comment]
> you don't register this model

你忘记注册你的model了吧
